conn:
    server: '127.0.0.1:57314'
    cert: ''
    timeout: 1m
    concurrency: 8
files:
    chunk: 32768
    patterns:
        - '/glob/to/your/files/*'
    # delete: true
response:
    log: 'strelka.log'
